[myhosts]
dev.learnkannada.co.in

[observability]
16.112.122.201

[myhosts:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/siva/.ssh/id_ed25519

[observability:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/siva/.ssh/id_ed25519